#
inherit_from: .rubocop_todo.yml
#
AllCops:
  NewCops: enable
# 文字列をフリーズする設定を無視
Style/FrozenStringLiteralComment:
  Enabled: false
# ドキュメントのないpublic classを許可
Style/Documentation:
  Enabled: false
# コントローラ等のモジュールをネストしての宣言
Style/ClassAndModuleChildren:
  Enabled: false
# シンボルによる配列の%記法のチェック
Style/SymbolArray:
  Enabled: false
  # EnforcedStyle: brackets
